# .coderabbit.yaml — versión moderna compatible
configVersion: 2

settings:
  language: "en"
  enableFreeTier: true
  review:
    enabled: true
    maxComments: 20
    tone: "professional"
    exclude:
      - vendor/
      - public/
      - storage/
      - node_modules/
      - .vscode/
    rules:
      - style
      - best_practices
      - performance
      - security
      - documentation
